import '../styles/globals.css';
import {AppProps} from "next/app";
import Head from "next/head";
import React from "react";

function MyApp({Component, pageProps}: AppProps): JSX.Element {
    return <>
        <Head>
            <title>My top - our best top</title>
            <meta name="description" content="Generated by create next app"/>
            <link key={1} rel="icon" href={"/favicon.ico"}/>
        </Head>

        <Component {...pageProps} />
    </>
}

export default MyApp
