import '../styles/globals.css';
import {AppProps} from "next/app";
import Head from "next/head";
import React from "react";

function MyApp({Component, pageProps}: AppProps): JSX.Element {
    return <>
        <Head>
            <title>My top - our best top</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@100;200;400;500;600;700&display=swap"
                rel="stylesheet"/>
        </Head>

        <Component {...pageProps} />
    </>
}

export default MyApp
